import { and, desc, eq, sql } from 'drizzle-orm';
import type { ProviderConnectionId, UserId, WorkspaceId } from '@relayd/types';
import { providerConnections } from '../schema/providers.js';
import type { ConnectionStatus, ProviderType } from '../schema/providers.js';
import type { WorkspaceScope } from '../scope.js';
import type { Executor } from './executor.js';

/**
 * Provider connections.
 *
 * Nothing here ever returns `credential_ref` or `webhook_secret_arn` to a
 * caller outside this file, and nothing accepts a credential. The API writes
 * the secret to Secrets Manager and stores the ARN; a Postgres dump therefore
 * contains no usable credential (INVARIANTS R21).
 *
 * `endpoint_token` is returned only by `createWithToken`, once. After that it
 * is readable by the ingest resolver and nowhere else — the UI shows the URL
 * at connect time and never again, because an endpoint token is a bearer
 * credential for writing events into a workspace (F4).
 */

export interface ProviderConnectionRow {
  id: ProviderConnectionId;
  workspaceId: WorkspaceId;
  providerType: ProviderType;
  name: string;
  status: ConnectionStatus;
  credentialVersion: number;
  config: Record<string, unknown>;
  capabilities: Record<string, unknown>;
  /** True when a webhook secret has been stored. Never the secret itself. */
  hasWebhookSecret: boolean;
  quotaSnapshot: Record<string, unknown> | null;
  quotaCheckedAt: Date | null;
  lastVerifiedAt: Date | null;
  lastError: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
}

export class ProviderConnectionRepository {
  constructor(private readonly db: Executor) {}

  /**
   * Creates a connection.
   *
   * The endpoint token is generated by the caller and returned here exactly
   * once, alongside the row. It is not on ProviderConnectionRow, so an
   * ordinary read cannot leak it into a list response.
   */
  async createWithToken(
    scope: WorkspaceScope,
    input: {
      id: ProviderConnectionId;
      providerType: ProviderType;
      name: string;
      credentialRef: string;
      endpointToken: string;
      config?: Record<string, unknown>;
      webhookSecretArn?: string;
      createdBy?: UserId;
    },
  ): Promise<{ connection: ProviderConnectionRow; endpointToken: string }> {
    const [row] = await this.db
      .insert(providerConnections)
      .values({
        id: input.id,
        workspaceId: scope.workspaceId,
        providerType: input.providerType,
        name: input.name,
        credentialRef: input.credentialRef,
        endpointToken: input.endpointToken,
        ...(input.config === undefined ? {} : { config: input.config }),
        ...(input.webhookSecretArn === undefined
          ? {}
          : { webhookSecretArn: input.webhookSecretArn }),
        ...(input.createdBy === undefined ? {} : { createdBy: input.createdBy }),
      })
      .returning();

    if (row === undefined) throw new Error('createConnection: insert returned no row');
    return { connection: toRow(row), endpointToken: input.endpointToken };
  }

  async findById(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
  ): Promise<ProviderConnectionRow | null> {
    const [row] = await this.db
      .select()
      .from(providerConnections)
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      )
      .limit(1);

    return row === undefined ? null : toRow(row);
  }

  async list(scope: WorkspaceScope): Promise<ProviderConnectionRow[]> {
    const rows = await this.db
      .select()
      .from(providerConnections)
      .where(eq(providerConnections.workspaceId, scope.workspaceId))
      .orderBy(desc(providerConnections.createdAt));

    return rows.map(toRow);
  }

  /**
   * The credential ARN, for the worker that is about to fetch it.
   *
   * Separate from findById so a route handler cannot return it by accident:
   * asking for it is a deliberate act with its own call.
   */
  async findCredentialRef(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
  ): Promise<{ credentialRef: string; credentialVersion: number } | null> {
    const [row] = await this.db
      .select({
        credentialRef: providerConnections.credentialRef,
        credentialVersion: providerConnections.credentialVersion,
      })
      .from(providerConnections)
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      )
      .limit(1);

    return row ?? null;
  }

  async rename(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
    name: string,
  ): Promise<ProviderConnectionRow | null> {
    const [row] = await this.db
      .update(providerConnections)
      .set({ name, updatedAt: new Date() })
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      )
      .returning();

    return row === undefined ? null : toRow(row);
  }

  /**
   * Records the outcome of a verification.
   *
   * `lastError` is cleared on success rather than left behind: a connection
   * showing an error it recovered from an hour ago sends people looking for a
   * problem that is not there.
   */
  async recordVerification(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
    result:
      | { ok: true; status: ConnectionStatus; capabilities?: Record<string, unknown> }
      | { ok: false; status: ConnectionStatus; error: Record<string, unknown> },
  ): Promise<boolean> {
    const rows = await this.db
      .update(providerConnections)
      .set({
        status: result.status,
        lastVerifiedAt: new Date(),
        updatedAt: new Date(),
        ...(result.ok
          ? {
              lastError: null,
              ...(result.capabilities === undefined ? {} : { capabilities: result.capabilities }),
            }
          : { lastError: result.error }),
      })
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      )
      .returning({ id: providerConnections.id });

    return rows.length > 0;
  }

  async recordQuota(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
    snapshot: Record<string, unknown>,
  ): Promise<void> {
    await this.db
      .update(providerConnections)
      .set({ quotaSnapshot: snapshot, quotaCheckedAt: new Date() })
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      );
  }

  /**
   * Points the connection at a new secret and bumps the version.
   *
   * The bump is what makes every worker's five-minute credential cache miss
   * immediately, so a rotation takes effect on the next send rather than up
   * to five minutes later (R21).
   */
  async rotateCredential(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
    credentialRef: string,
  ): Promise<number | null> {
    const [row] = await this.db
      .update(providerConnections)
      .set({
        credentialRef,
        credentialVersion: sql`${providerConnections.credentialVersion} + 1`,
        status: 'verifying',
        updatedAt: new Date(),
      })
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      )
      .returning({ credentialVersion: providerConnections.credentialVersion });

    return row?.credentialVersion ?? null;
  }

  async setWebhookSecretArn(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
    arn: string,
  ): Promise<boolean> {
    const rows = await this.db
      .update(providerConnections)
      .set({ webhookSecretArn: arn, updatedAt: new Date() })
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      )
      .returning({ id: providerConnections.id });

    return rows.length > 0;
  }

  /**
   * A guarded status transition.
   *
   * Guarded rather than a blind write so two concurrent actors — an operator
   * disabling a connection and a worker marking it degraded — cannot
   * overwrite each other's decision. Zero rows means the caller lost.
   */
  async transition(
    scope: WorkspaceScope,
    id: ProviderConnectionId,
    from: readonly ConnectionStatus[],
    to: ConnectionStatus,
  ): Promise<boolean> {
    const rows = await this.db
      .update(providerConnections)
      .set({ status: to, updatedAt: new Date() })
      .where(
        and(
          eq(providerConnections.id, id),
          eq(providerConnections.workspaceId, scope.workspaceId),
          sql`${providerConnections.status} = ANY(${sql.param(from)})`,
        ),
      )
      .returning({ id: providerConnections.id });

    return rows.length > 0;
  }

  /**
   * Removes a connection.
   *
   * A hard delete, not a soft one. A disconnected provider must stop being
   * reachable: leaving the row means the endpoint token still resolves, and
   * an endpoint token is a bearer credential for writing events into this
   * workspace. Senders and identities cascade; the caller destroys the
   * Secrets Manager entry.
   */
  async remove(scope: WorkspaceScope, id: ProviderConnectionId): Promise<boolean> {
    const rows = await this.db
      .delete(providerConnections)
      .where(
        and(eq(providerConnections.id, id), eq(providerConnections.workspaceId, scope.workspaceId)),
      )
      .returning({ id: providerConnections.id });

    return rows.length > 0;
  }
}

function toRow(row: typeof providerConnections.$inferSelect): ProviderConnectionRow {
  return {
    id: row.id,
    workspaceId: row.workspaceId,
    providerType: row.providerType,
    name: row.name,
    status: row.status,
    credentialVersion: row.credentialVersion,
    config: (row.config as Record<string, unknown> | null) ?? {},
    capabilities: (row.capabilities as Record<string, unknown> | null) ?? {},
    // Presence, never the value. The ARN is not a secret, but it names one,
    // and there is no reason for a list response to carry it.
    hasWebhookSecret: row.webhookSecretArn !== null,
    quotaSnapshot: (row.quotaSnapshot as Record<string, unknown> | null) ?? null,
    quotaCheckedAt: row.quotaCheckedAt,
    lastVerifiedAt: row.lastVerifiedAt,
    lastError: (row.lastError as Record<string, unknown> | null) ?? null,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}
