import nodemailer from 'nodemailer';
import { providerError } from '../../errors.js';
import { classifySmtpError } from './errors.js';
import type {
  EmailProviderAdapter,
  NormalisedEmailEvent,
  OutboundMessage,
  ProviderCapabilities,
  ProviderCredentials,
  QuotaSnapshot,
  SendOutcome,
  SenderIdentitySnapshot,
  VerificationResult,
} from '../../port.js';

/**
 * SMTP.
 *
 * The honest adapter. SMTP gives no delivery feedback beyond what the server
 * says at the moment of the transaction: no webhooks, no bounce notifications,
 * no complaint reports, no quota. A workspace sending over SMTP accumulates
 * bad addresses invisibly, which is why D4 labels SMTP best-effort in the UI
 * and why `supportsWebhooks` is false here — the campaign UI reads that and
 * tells the customer what they are not getting.
 *
 * `maxBatchSize` is 1. SMTP has no batch verb; a "batch" is one connection
 * reused for several transactions, which is what the pooled transport does.
 */

const CAPABILITIES: ProviderCapabilities = {
  maxBatchSize: 1,
  // No webhooks at all. This is the whole reason for D4.
  supportsWebhooks: false,
  supportsTracking: false,
  supportsCustomHeaders: true,
  supportsScheduling: false,
  supportsSuppressionSync: false,
  // Message-ID is generated by us, not returned by the server; the server's
  // accept response may carry a queue id, which is not the same thing.
  returnsMessageId: false,
  reportsQuota: false,
  maxRecipientsPerMessage: 1,
  // Conservative: many servers refuse above 10 MB and most refuse above 25.
  maxMessageBytes: 10 * 1024 * 1024,
};

/** What the adapter needs from a transport. Lets tests supply one. */
export interface SmtpTransport {
  sendMail(options: Record<string, unknown>): Promise<{ messageId?: string; response?: string }>;
  verify?(): Promise<boolean>;
  close?(): void;
}

export interface SmtpTransportFactory {
  (credentials: Extract<ProviderCredentials, { type: 'smtp' }>): SmtpTransport;
}

function defaultTransportFactory(
  credentials: Extract<ProviderCredentials, { type: 'smtp' }>,
): SmtpTransport {
  return nodemailer.createTransport({
    host: credentials.host,
    port: credentials.port,
    secure: credentials.secure,
    auth: { user: credentials.user, pass: credentials.pass },

    // Pooled, because the cost of SMTP is the handshake: a TCP connect, a
    // TLS negotiation and an AUTH exchange per message would make a 50,000
    // recipient campaign take hours.
    pool: true,
    maxConnections: 5,
    maxMessages: 100,

    // The wrapper owns the overall timeout; these stop a single stage from
    // hanging past it. 60s for SMTP per CLAUDE.md section 9.
    connectionTimeout: 20_000,
    greetingTimeout: 20_000,
    socketTimeout: 60_000,
  }) as unknown as SmtpTransport;
}

function requireSmtpCredentials(
  credentials: ProviderCredentials,
): Extract<ProviderCredentials, { type: 'smtp' }> {
  if (credentials.type !== 'smtp') {
    throw providerError('auth_failed', 'These are not SMTP credentials');
  }
  return credentials;
}

export function createSmtpAdapter(
  transportFactory: SmtpTransportFactory = defaultTransportFactory,
): EmailProviderAdapter {
  const transportFor = (credentials: ProviderCredentials): SmtpTransport =>
    transportFactory(requireSmtpCredentials(credentials));

  const sendOne = async (
    credentials: ProviderCredentials,
    message: OutboundMessage,
  ): Promise<SendOutcome> => {
    try {
      const transport = transportFor(credentials);
      const result = await transport.sendMail(buildMail(message));

      return {
        ok: true,
        recipientId: message.recipientId,
        // The server's queue id where it gave one. Not a provider message id
        // in the sense the other adapters mean — nothing will ever reference
        // it back to us, because there are no webhooks.
        providerMessageId: result.messageId ?? null,
        acceptedAt: new Date(),
      };
    } catch (cause) {
      return { ok: false, recipientId: message.recipientId, error: classifySmtpError(cause) };
    }
  };

  return {
    type: 'smtp',
    capabilities: CAPABILITIES,

    async verifyConnection(credentials): Promise<VerificationResult> {
      try {
        const transport = transportFor(credentials);

        if (transport.verify !== undefined) await transport.verify();

        const smtp = requireSmtpCredentials(credentials);
        return {
          ok: true,
          details: {
            host: smtp.host,
            port: smtp.port,
            secure: smtp.secure,
            // Read by the UI to show the best-effort label (D4).
            deliveryFeedback: false,
          },
        };
      } catch (cause) {
        return { ok: false, error: classifySmtpError(cause) };
      }
    },

    /** SMTP reports nothing. Returning null is the honest answer. */
    async getQuota(): Promise<QuotaSnapshot | null> {
      return null;
    },

    /**
     * SMTP has no concept of a verified identity.
     *
     * Returning [] rather than inventing one: the server will accept or
     * refuse the MAIL FROM at send time, and claiming an identity is verified
     * when nothing verified it would put a green tick next to a guess.
     */
    async listVerifiedIdentities(): Promise<SenderIdentitySnapshot[]> {
      return [];
    },

    send: sendOne,

    async sendBatch(credentials, messages): Promise<SendOutcome[]> {
      if (messages.length === 0) return [];

      // Sequential, deliberately. The pooled transport already runs several
      // connections; firing every message at once would open as many as the
      // array is long and get the customer's server to refuse the lot.
      const outcomes: SendOutcome[] = [];
      for (const message of messages) outcomes.push(await sendOne(credentials, message));
      return outcomes;
    },

    /**
     * SMTP has no webhooks, so there is no signature to verify.
     *
     * Returns false rather than true. An endpoint that somehow received a
     * payload for an SMTP connection is receiving something nobody sent, and
     * accepting it would let anyone write events against an SMTP workspace.
     */
    verifyWebhookSignature(): boolean {
      return false;
    },

    parseWebhook(): NormalisedEmailEvent[] {
      return [];
    },
  };
}

function buildMail(message: OutboundMessage): Record<string, unknown> {
  const listUnsubscribe = message.listUnsubscribe.mailto
    ? `<${message.listUnsubscribe.mailto}>, <${message.listUnsubscribe.url}>`
    : `<${message.listUnsubscribe.url}>`;

  const headers: Record<string, string> = {
    ...message.headers,
    'List-Unsubscribe': listUnsubscribe,
  };

  if (message.listUnsubscribe.oneClick) {
    headers['List-Unsubscribe-Post'] = 'List-Unsubscribe=One-Click';
  }

  return {
    from: { name: message.from.name, address: message.from.email },
    to: message.to.name === undefined
      ? message.to.email
      : { name: message.to.name, address: message.to.email },
    ...(message.replyTo === undefined ? {} : { replyTo: message.replyTo }),
    subject: message.subject,
    text: message.text,
    html: message.html,
    headers,
    ...(message.attachments === undefined
      ? {}
      : {
          attachments: message.attachments.map((attachment) => ({
            filename: attachment.filename,
            contentType: attachment.contentType,
            content: attachment.contentBase64,
            encoding: 'base64',
          })),
        }),
  };
}
